services:
  webdriver:
    image: "selenium/standalone-chrome:latest"
    ports:
      - 4444:4444

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - 5432:5432
